### PR TITLE
Changes for adding recordng start/stop feature for Group calling hero…

### PR DESCRIPTION
**Pull request by ravithanneeru**
… sample

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by alkwa-msft** [comment]
Can we move this into the teams interop branch? main is designed to only be using the GA sdks

**Comment by ravithanneeru** [comment]
> Can we move this into the teams interop branch? main is designed to only be using the GA sdks

Yes Alex, will move to interop branch. These changes were pushed when we don't have full clarify on where to merge recording changes.

**Comment by alkwa-msft** [comment]
sorry. I have created a public-preview branch which is essentially the teams-interop branch. lets move it there!

**Comment by alkwa-msft** [comment]
Closing out this PR since we've added it to public-preview

**Pull request closed without merging**
