### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by magnoeasy**
## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by alex-kwan** [comment]
Hi, I was wondering what version of node are you running when you are building. Prior to release I was trying to investigate this problem and I found that running on a more recent version of node (12.13.0) seemed to work better than having alot of memory. This could be related to better garbage collection strategies in later versions of node @magnoeasy

**Comment by magnoeasy** [comment]
v10.16.3

**Comment by alex-kwan** [comment]
Hi @magnoeasy I was wondering if you can upgrade your version of node? In the readme it looks like we are supporting node 12 and later

**Comment by magnoeasy** [comment]
For sure, I didn't realize at first that was a problem with the node
version.

**Comment by alex-kwan** [comment]
Yeah its just an improvement on the garbage collection rather than any critical new features. Please reply back if it work or it didn't work. I would love to be able to help you further if we are still running into issues or be able to close this if your good to go!

**Comment by magnoeasy** [comment]
I updated to Node version 15 and solved the problem.

**Comment by alex-kwan** [comment]
Just in case anyone is reading this. We are closing this because the answer is updating the version of node to match what is stated in the readme as opposed to allocating additional memory for the node process!

**Pull request closed without merging**
